name: Vorn.Aaas.Client.Js

on:
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: read

jobs:
  run:
    permissions:
      checks: write
      contents: read
    name: Vorn.Aaas.Client.Js
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}
          cache: npm

      - name: Install npm dependencies
        run: npm ci

      - name: Run dist
        run: npm run js
        
      - name: Minify
        uses: devatherock/minify-js@v3.1.0
        with:
          directory: dist/js
          output: dist/js/min
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Vorn.Aaas.Client.Bootstrap.Js
          path: dist/js/min 
